openapi: 3.0.3
info:
  title: Individual Employment
  description: "# Data availability\n\nData is only available for taxpayers who are\
    \ registered for Self Assessment and had any employments in the given tax year.\n\
    \nAlso, data is only available once PAYE reconciliation has completed. This is\
    \ the process that determines whether the individual has paid the right amount\
    \ of tax and, for PAYE-only taxpayers, results in a P800 in the event of [overpayment\
    \ or underpayment.](https://www.gov.uk/tax-overpayments-and-underpayments)\n\n\
    Reconciliation starts on or around 6th June and runs for around one million individuals\
    \ per working night. It has usually completed by the end of November. Unfortunately\
    \ it is not possible to know when reconciliation will be complete for a specific\
    \ individual.\n\nIf we are expecting a P11D, reconciliation will not start for\
    \ that individual until we have received and processed the P11D. If we receive\
    \ a P11D unexpectedly, we will re-run the reconciliation.\n\nData is no longer\
    \ available once we have received and processed the corresponding Self Assessment\
    \ return.\n\n# Data quality\n\nThe data from this API is based on information\
    \ we receive from employers and pension providers.\n\nNote that:\n\n- Pension\
    \ providers sometimes don't tell us that income has come from a pension. In these\
    \ cases, \nthe API reports the income source as an employment.\n- If the individual\
    \ received a State Pension lump sum in the given tax year, \nthis API will report\
    \ it as an employment with a specific PAYE reference of `267/LS500`.\n\n# Authorisation\n\
    \nThe endpoint in this API is [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints).\
    \ \nYour users must grant authority for your software to access it by signing\
    \ in to their HMRC online account.\n\nThe API supports individual and agent users.\
    \ Note that:\n- Individual users can only access their own information.\n- Agent\
    \ users can only access their own clients’ data.\n\nThe following options are\
    \ supported for agents:\n\n**Option 1: Agent services account**\n\nIf the agent\
    \ uses an [agent services account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#agent-services-account),\n\
    they can access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)\n\
    who they have [linked to their agent services account](https://www.gov.uk/guidance/link-clients-to-your-agent-services-account#link-existing-clients)\n\
    (restricted to 2 years’ history)\n\n**Option 2: HMRC online services for agents\
    \ account**\n\nIf the agent uses an [HMRC online services for agents account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#hmrc-online-services-for-agents-account)\n\
    which is enrolled for [Self Assessment for Agents](https://www.gov.uk/guidance/self-assessment-for-agents-online-service),\n\
    they will be able to access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)\n\
    (restricted to 2 years’ history).\n"
  version: "1.2"
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
paths:
  /individual-employment/sa/{utr}/annual-summary/{taxYear}:
    get:
      tags:
      - individual-employment
      summary: Get employment history
      description: Fetches an individual’s employment history for the given tax year.
      operationId: getEmploymentHistory
      parameters:
      - name: utr
        in: path
        description: The 10 digit self-assessment UTR for the individual.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: "2234567890"
      - name: taxYear
        in: path
        description: The tax year for the income being retrieved.
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[0-9]{4}-[0-9]{2}$"
          type: string
          example: 2016-17
      - name: Accept
        in: header
        description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
          \ of the API to be used."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/vnd.hmrc.1.2+json
      - name: Authorization
        in: header
        description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints)\
          \ with the `read:individual-employment` scope."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                required:
                - employments
                type: object
                properties:
                  employments:
                    type: array
                    description: An unordered list of one or more employments which
                      the taxpayer had in the given tax year.
                    items:
                      title: employment
                      required:
                      - employerName
                      - employerPayeReference
                      type: object
                      properties:
                        employerPayeReference:
                          type: string
                          description: The employer’s PAYE reference. A value of 267/LS500
                            indicates a State Pension lump sum.
                          example: 123/AB456
                        employerName:
                          type: string
                          description: The name of the employer.
                          example: Company XYZ
                        offPayrollWorkFlag:
                          type: boolean
                          description: The value of OPW flag.
                          example: false
                description: Employers PAYE Charges
              example:
                employments:
                - employerPayeReference: 123/AB456
                  employerName: Company XYZ
                  offPayrollWorkFlag: true
                - employerPayeReference: 456/AB456
                  employerName: Company ABC
                  offPayrollWorkFlag: false
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - code
                - message
                type: object
                properties:
                  code:
                    type: string
                    description: The error code
                  message:
                    type: string
                    description: The error message
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                    message: The provided SA UTR is invalid
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                    message: The provided Tax Year is invalid
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                required:
                - code
                - message
                type: object
                properties:
                  code:
                    type: string
                    description: The error code
                  message:
                    type: string
                    description: The error message
              examples:
                unauthorisedUser:
                  description: User not authorised to access data for given UTR
                  value:
                    code: UNAUTHORIZED
                    message: Bearer token is missing or not authorized
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                required:
                - code
                - message
                type: object
                properties:
                  code:
                    type: string
                    description: The error code
                  message:
                    type: string
                    description: The error message
              examples:
                unmatchedRecipient:
                  description: Data not available for given UTR and tax year (see
                    the data availability section for more details)
                  value:
                    code: NOT_FOUND
                    message: Resource was not found
      deprecated: false
      security:
      - user-restricted:
        - read:individual-employment
components:
  schemas:
    errorResponse:
      title: errorResponse
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
    employment:
      title: employment
      required:
      - employerName
      - employerPayeReference
      type: object
      properties:
        employerPayeReference:
          type: string
          description: The employer’s PAYE reference. A value of 267/LS500 indicates
            a State Pension lump sum.
          example: 123/AB456
        employerName:
          type: string
          description: The name of the employer.
          example: Company XYZ
        offPayrollWorkFlag:
          type: boolean
          description: The value of OPW flag.
          example: false
    individualEmploymentSaAnnualSummaryResponse:
      title: individualEmploymentSaAnnualSummaryResponse
      required:
      - employments
      type: object
      properties:
        employments:
          type: array
          description: An unordered list of one or more employments which the taxpayer
            had in the given tax year.
          items:
            title: employment
            required:
            - employerName
            - employerPayeReference
            type: object
            properties:
              employerPayeReference:
                type: string
                description: The employer’s PAYE reference. A value of 267/LS500 indicates
                  a State Pension lump sum.
                example: 123/AB456
              employerName:
                type: string
                description: The name of the employer.
                example: Company XYZ
              offPayrollWorkFlag:
                type: boolean
                description: The value of OPW flag.
                example: false
      description: Employers PAYE Charges
  parameters:
    utr:
      name: utr
      in: path
      description: The 10 digit self-assessment UTR for the individual.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: "2234567890"
    taxYear:
      name: taxYear
      in: path
      description: The tax year for the income being retrieved.
      required: true
      style: simple
      explode: false
      schema:
        pattern: "^[0-9]{4}-[0-9]{2}$"
        type: string
        example: 2016-17
    acceptHeader:
      name: Accept
      in: header
      description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
        \ of the API to be used."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/vnd.hmrc.1.2+json
    authorizationHeader:
      name: Authorization
      in: header
      description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ with the `read:individual-employment` scope."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  securitySchemes:
    user-restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ API requests using an OAuth 2.0 Bearer Token in the Authorization header."
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:individual-employment: Access employment history
